In [5]:
import matplotlib.pyplot as plt
import numpy as np

In [6]:
CW = 2
TILT = 30 # latitude tilt but minimum is around 30 (south florida)

ground_pannel_proj = CW * np.cos(np.deg2rad(TILT)) # xp from spreadsheet

In [7]:
pitches = np.linspace(3.8, 12, 1000)

In [8]:
pitches

array([ 3.8       ,  3.80820821,  3.81641642,  3.82462462,  3.83283283,
        3.84104104,  3.84924925,  3.85745746,  3.86566567,  3.87387387,
        3.88208208,  3.89029029,  3.8984985 ,  3.90670671,  3.91491491,
        3.92312312,  3.93133133,  3.93953954,  3.94774775,  3.95595596,
        3.96416416,  3.97237237,  3.98058058,  3.98878879,  3.996997  ,
        4.00520521,  4.01341341,  4.02162162,  4.02982983,  4.03803804,
        4.04624625,  4.05445445,  4.06266266,  4.07087087,  4.07907908,
        4.08728729,  4.0954955 ,  4.1037037 ,  4.11191191,  4.12012012,
        4.12832833,  4.13653654,  4.14474474,  4.15295295,  4.16116116,
        4.16936937,  4.17757758,  4.18578579,  4.19399399,  4.2022022 ,
        4.21041041,  4.21861862,  4.22682683,  4.23503504,  4.24324324,
        4.25145145,  4.25965966,  4.26786787,  4.27607608,  4.28428428,
        4.29249249,  4.3007007 ,  4.30890891,  4.31711712,  4.32532533,
        4.33353353,  4.34174174,  4.34994995,  4.35815816,  4.36

In [9]:
edgetoedge = pitches - ground_pannel_proj

In [10]:
edgetoedge

array([ 2.06794919,  2.0761574 ,  2.08436561,  2.09257382,  2.10078203,
        2.10899023,  2.11719844,  2.12540665,  2.13361486,  2.14182307,
        2.15003127,  2.15823948,  2.16644769,  2.1746559 ,  2.18286411,
        2.19107232,  2.19928052,  2.20748873,  2.21569694,  2.22390515,
        2.23211336,  2.24032156,  2.24852977,  2.25673798,  2.26494619,
        2.2731544 ,  2.28136261,  2.28957081,  2.29777902,  2.30598723,
        2.31419544,  2.32240365,  2.33061186,  2.33882006,  2.34702827,
        2.35523648,  2.36344469,  2.3716529 ,  2.3798611 ,  2.38806931,
        2.39627752,  2.40448573,  2.41269394,  2.42090215,  2.42911035,
        2.43731856,  2.44552677,  2.45373498,  2.46194319,  2.47015139,
        2.4783596 ,  2.48656781,  2.49477602,  2.50298423,  2.51119244,
        2.51940064,  2.52760885,  2.53581706,  2.54402527,  2.55223348,
        2.56044168,  2.56864989,  2.5768581 ,  2.58506631,  2.59327452,
        2.60148273,  2.60969093,  2.61789914,  2.62610735,  2.63

In [11]:
under_pannel_percent = ground_pannel_proj * 100 / pitches
edgetoedge_percent = edgetoedge * 100 / pitches

edgetoedge_percent

array([54.41971559, 54.51795929, 54.61578039, 54.71318162, 54.81016566,
       54.9067352 , 55.00289289, 55.09864135, 55.1939832 , 55.28892101,
       55.38345736, 55.47759477, 55.57133578, 55.66468287, 55.75763854,
       55.85020523, 55.94238538, 56.0341814 , 56.1255957 , 56.21663065,
       56.3072886 , 56.3975719 , 56.48748286, 56.57702377, 56.66619693,
       56.75500458, 56.84344898, 56.93153234, 57.01925687, 57.10662477,
       57.1936382 , 57.28029931, 57.36661024, 57.45257311, 57.53819002,
       57.62346305, 57.70839427, 57.79298574, 57.87723948, 57.96115751,
       58.04474185, 58.12799446, 58.21091734, 58.29351242, 58.37578165,
       58.45772696, 58.53935025, 58.62065342, 58.70163834, 58.78230689,
       58.86266091, 58.94270224, 59.0224327 , 59.1018541 , 59.18096823,
       59.25977687, 59.33828179, 59.41648474, 59.49438745, 59.57199166,
       59.64929908, 59.72631141, 59.80303032, 59.8794575 , 59.95559461,
       60.0314433 , 60.10700519, 60.18228192, 60.2572751 , 60.33

In [12]:
under_pannel_blocks = np.round(under_pannel_percent / 10)
under_pannel_blocks

array([5., 5., 5., 5., 5., 5., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3.

In [13]:
edgetoedge_blocks = np.round(edgetoedge_percent / 10)
edgetoedge_blocks

array([5., 5., 5., 5., 5., 5., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
       7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
       7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
       7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
       7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
       7., 7., 7., 7., 7.

In [14]:
under_pannel_blocks + edgetoedge_blocks

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10

In [74]:
outputs = []

prev_val = under_pannel_blocks[0]
for i in range(1, len(pitches)):
    cur_val = under_pannel_blocks[i]
    
    if prev_val != cur_val:
        outputs.append(i)

    prev_val = cur_val

outputs

[6, 140, 382, 944]

In [76]:
for n in pitches[outputs]:
    print(n)

3.849249249249249
4.949149149149148
6.935535535535536
11.548548548548547
