In [2]:
import matplotlib.pyplot as plt
import numpy as np

In [3]:
CW = 2
TILT = 30 # latitude tilt but minimum is around 30 (south florida)

ground_pannel_proj = CW * np.cos(np.deg2rad(TILT)) # xp from spreadsheet

In [4]:
pitches = np.linspace(3.8, 24, 1000)

In [5]:
pitches

array([ 3.8       ,  3.82022022,  3.84044044,  3.86066066,  3.88088088,
        3.9011011 ,  3.92132132,  3.94154154,  3.96176176,  3.98198198,
        4.0022022 ,  4.02242242,  4.04264264,  4.06286286,  4.08308308,
        4.1033033 ,  4.12352352,  4.14374374,  4.16396396,  4.18418418,
        4.2044044 ,  4.22462462,  4.24484484,  4.26506507,  4.28528529,
        4.30550551,  4.32572573,  4.34594595,  4.36616617,  4.38638639,
        4.40660661,  4.42682683,  4.44704705,  4.46726727,  4.48748749,
        4.50770771,  4.52792793,  4.54814815,  4.56836837,  4.58858859,
        4.60880881,  4.62902903,  4.64924925,  4.66946947,  4.68968969,
        4.70990991,  4.73013013,  4.75035035,  4.77057057,  4.79079079,
        4.81101101,  4.83123123,  4.85145145,  4.87167167,  4.89189189,
        4.91211211,  4.93233233,  4.95255255,  4.97277277,  4.99299299,
        5.01321321,  5.03343343,  5.05365365,  5.07387387,  5.09409409,
        5.11431431,  5.13453453,  5.15475475,  5.17497497,  5.19

In [14]:
edgetoedge = pitches - ground_pannel_proj

In [15]:
edgetoedge

array([ 2.06794919,  2.08816941,  2.10838963,  2.12860985,  2.14883007,
        2.16905029,  2.18927051,  2.20949073,  2.22971095,  2.24993117,
        2.27015139,  2.29037161,  2.31059184,  2.33081206,  2.35103228,
        2.3712525 ,  2.39147272,  2.41169294,  2.43191316,  2.45213338,
        2.4723536 ,  2.49257382,  2.51279404,  2.53301426,  2.55323448,
        2.5734547 ,  2.59367492,  2.61389514,  2.63411536,  2.65433558,
        2.6745558 ,  2.69477602,  2.71499624,  2.73521646,  2.75543668,
        2.7756569 ,  2.79587712,  2.81609734,  2.83631756,  2.85653778,
        2.876758  ,  2.89697822,  2.91719844,  2.93741866,  2.95763888,
        2.9778591 ,  2.99807932,  3.01829954,  3.03851976,  3.05873998,
        3.0789602 ,  3.09918042,  3.11940064,  3.13962086,  3.15984108,
        3.1800613 ,  3.20028152,  3.22050174,  3.24072197,  3.26094219,
        3.28116241,  3.30138263,  3.32160285,  3.34182307,  3.36204329,
        3.38226351,  3.40248373,  3.42270395,  3.44292417,  3.46

In [16]:
under_pannel_percent = ground_pannel_proj * 100 / pitches
edgetoedge_percent = edgetoedge * 100 / pitches

edgetoedge_percent

array([54.41971559, 54.66096958, 54.89968314, 55.13589616, 55.36964775,
       55.60097617, 55.82991891, 56.05651268, 56.28079345, 56.50279646,
       56.72255623, 56.94010659, 57.15548069, 57.36871103, 57.57982945,
       57.78886718, 57.99585481, 58.20082238, 58.4037993 , 58.60481443,
       58.80389608, 59.00107201, 59.19636946, 59.38981513, 59.58143525,
       59.77125554, 59.95930123, 60.14559709, 60.33016744, 60.51303613,
       60.6942266 , 60.87376183, 61.05166441, 61.22795651, 61.4026599 ,
       61.57579595, 61.74738567, 61.91744967, 62.08600822, 62.25308122,
       62.41868822, 62.58284844, 62.74558074, 62.90690369, 63.0668355 ,
       63.2253941 , 63.3825971 , 63.5384618 , 63.69300523, 63.84624411,
       63.9981949 , 64.14887376, 64.2982966 , 64.44647907, 64.59343653,
       64.73918412, 64.88373672, 65.02710897, 65.16931526, 65.31036975,
       65.4502864 , 65.5890789 , 65.72676075, 65.86334523, 65.99884542,
       66.13327416, 66.26664412, 66.39896775, 66.53025733, 66.66

In [17]:
under_pannel_blocks = np.round(under_pannel_percent / 10)
under_pannel_blocks

array([5., 5., 5., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2.

In [ ]:
edgetoedge_blocks = np.round(edgetoedge_percent / 10)
edgetoedge_blocks

array([5., 5., 5., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
       7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
       7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
       7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
       7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
       7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.,
       7., 7., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
       8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
       8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
       8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
       8., 8., 8., 8., 8.

In [ ]:
shape = under_pannel_blocks
conf_array = np.ones_like(shape) * 10.0

# check that all under pannel counts + inter-row counts are the same
check_array = under_pannel_blocks + edgetoedge_blocks
np.testing.assert_array_equal(check_array, conf_array)

In [20]:
outputs = []

prev_val = under_pannel_blocks[0]
for i in range(1, len(pitches)):
    cur_val = under_pannel_blocks[i]
    
    if prev_val != cur_val:
        outputs.append(i)

    prev_val = cur_val

outputs

[3, 57, 155, 384]

In [21]:
for n in pitches[outputs]:
    print(n)

3.8606606606606606
4.952552552552552
6.934134134134134
11.564564564564565
