In [2]:
import numpy as np
import xarray as xr
import inspire_agrivolt

In [9]:
model_outs = xr.open_zarr("/projects/inspire/PySAM-MAPS/v1.1/colorado/06/389874-393329.zarr")

model_outs

<xarray.Dataset> Size: 493MB
Dimensions:              (gid: 320, time: 8760, distance: 10)
Coordinates:
  * distance             (distance) int64 80B 0 1 2 3 4 5 6 7 8 9
  * gid                  (gid) int64 3kB 389874 389875 389876 ... 393328 393329
  * time                 (time) datetime64[ns] 70kB 2001-01-01 ... 2001-12-31...
Data variables: (12/17)
    albedo               (gid, time) float64 22MB dask.array<chunksize=(40, 8760), meta=np.ndarray>
    annual_energy        (gid) float64 3kB dask.array<chunksize=(40,), meta=np.ndarray>
    annual_poa           (gid) float64 3kB dask.array<chunksize=(40,), meta=np.ndarray>
    dhi                  (gid, time) float64 22MB dask.array<chunksize=(40, 8760), meta=np.ndarray>
    dni                  (gid, time) float64 22MB dask.array<chunksize=(40, 8760), meta=np.ndarray>
    ghi                  (gid, time) float64 22MB dask.array<chunksize=(40, 8760), meta=np.ndarray>
    ...                   ...
    subarray1_poa_front  (gid, time) float64 22MB dask.array<chunksize=(40, 8760), meta=np.ndarray>
    subarray1_poa_rear   (gid, time) float64 22MB dask.array<chunksize=(40, 8760), meta=np.ndarray>
    temp_air             (gid, time) float64 22MB dask.array<chunksize=(40, 8760), meta=np.ndarray>
    tilt                 (gid) float64 3kB dask.array<chunksize=(40,), meta=np.ndarray>
    wind_direction       (gid, time) float64 22MB dask.array<chunksize=(40, 8760), meta=np.ndarray>
    wind_speed           (gid, time) float64 22MB dask.array<chunksize=(40, 8760), meta=np.ndarray>
Attributes:
    kestrel_nsrdb_fnames:  ['/datasets/NSRDB/current/nsrdb_tmy-2024.h5']
    software_versions:     {'dask': '2024.8.0', 'dask_jobqueue': '0.8.5', 'fs...

In [10]:
inspire_agrivolt.ground_irradiance_distances(model_outs).values

array([[0.22210757, 0.66632271, 1.11053784, ..., 3.33161353, 3.77582866,
        4.2200438 ],
       [0.22174512, 0.66523535, 1.10872559, ..., 3.32617677, 3.76966701,
        4.21315724],
       [0.2213841 , 0.66415229, 1.10692048, ..., 3.32076143, 3.76352962,
        4.20629781],
       ...,
       [0.24250203, 0.72750609, 1.21251016, ..., 3.63753047, 4.12253453,
        4.6075386 ],
       [0.24206511, 0.72619533, 1.21032554, ..., 3.63097663, 4.11510684,
        4.59923706],
       [0.2416297 , 0.7248891 , 1.2081485 , ..., 3.6244455 , 4.1077049 ,
        4.5909643 ]])

In [11]:
model_outs.pitch.values

array([4.44215137, 4.43490236, 4.42768191, 4.42048856, 4.41332297,
       4.40618506, 4.39907546, 4.39199274, 4.93005369, 4.92104113,
       4.91205915, 4.90310772, 4.89418766, 4.88529723, 4.87643726,
       4.86760772, 4.85880941, 4.85004063, 4.84130217, 4.832594  ,
       4.82391693, 4.81526924, 4.80665175, 4.79806441, 4.78950799,
       4.78098084, 4.77248373, 4.76401662, 4.75557946, 4.74717303,
       4.73879568, 4.73044816, 4.72213045, 4.71384328, 4.70558502,
       4.69735644, 4.68915749, 4.68098889, 4.67284905, 4.6647387 ,
       4.6566578 , 4.64860706, 4.6405849 , 4.63259205, 4.62462846,
       4.61669483, 4.6087896 , 4.60091348, 4.59306643, 4.58524913,
       4.57746005, 4.56969987, 4.56196855, 4.55426604, 4.54659301,
       4.53894795, 4.53133154, 4.52374373, 4.51618517, 4.50865438,
       4.50115202, 4.49367804, 4.48623308, 4.47881568, 4.47142649,
       4.46406545, 4.45673321, 4.4494283 , 4.44215137, 4.43490236,
       4.42768191, 4.42048856, 4.41332297, 4.40618506, 4.39907

In [12]:
NUM_BEDS = 10
pitch = 4.832594  # [m]

bed_size = pitch / NUM_BEDS
np.arange(bed_size / 2, pitch, bed_size)

array([0.2416297, 0.7248891, 1.2081485, 1.6914079, 2.1746673, 2.6579267,
       3.1411861, 3.6244455, 4.1077049, 4.5909643])

In [43]:
((np.arange(NUM_BEDS) + 0.5) / NUM_BEDS) * 8


array([0.4, 1.2, 2. , 2.8, 3.6, 4.4, 5.2, 6. , 6.8, 7.6])